### ISSUE TITLE
$createUser promise not returning user object

### ISSUE THREAD

**Issue by edwinwright** [firebase/angularfire#507]
I'm trying to create a new user, then grab the uid so that I can save additional user data during registration. I'm finding that there is no user object being returning as per the doco in https://github.com/firebase/angularfire/blob/master/src/FirebaseAuth.js.

Here is my Authentication service...

```
myApp.factory('Authentication',
  function($firebaseAuth, FIREBASE_URL, $location) {

  var ref = new Firebase(FIREBASE_URL);
  var authObj = $firebaseAuth(ref);

  var myObj = {
    register: function(user) {
      return authObj.$createUser(user.email, user.password)
        .then(function(authData) {

          console.log(authData); // returns undefined

        });
    },

    login: function(user) {
      return authObj.$authWithPassword({
        email: user.email,
        password: user.password
      });
    },

    logout: function() {
      return authObj.$unauth();
    }
  }

  return myObj;

});
```

**Comment by pruchai** [comment]
This seems to affect both, legacy Simple Login and the new built-in Firebase Auth.
 
Hopefully this is going to be fixed in the next few days. This feature is rather useless without user object being returned.

**Comment by ChrisSoto** [comment]
Seems fixed now.

**Comment by jwngr** [comment]
Yes, as of AngularFire 0.9.1 (which was released yesterday), the `$createUser()` method now returns a user object containing the `uid` of the created user. Please upgrade to AngularFire 0.9.1 or later if you need this functionality.

**Comment by earthcrosser** [comment]
I have still not been able to get the userData back from the $createUser method.  I am using the cdn  to import code into my project and I have Firebase version 2.0.4 and AngularFire 0.9.1.  I have a simple controller which has the example code from the docs pretty much exactly copied and pasted.  After successfully creating a user console log reports "cannot read property 'uid' of undefined"

**Comment by jwngr** [comment]
The user data was not exposed from the Firebase client until version 2.0.5 ([here is the full changelog for the client](https://www.firebase.com/docs/web/changelog.html)). Just upgrade your Firebase version and you'll be all set. The latest version (which is 2.1.1 as of this comment) is fully compatible AngularFire 0.9.1 so I'd suggest upgrading to that.

**Comment by earthcrosser** [comment]
That was it, thanks jwngr!
