### ISSUE TITLE
Key X was undefined. Cannot pass undefined in JSON. Use null instead.

### ISSUE THREAD

**Issue by semeano** [firebase/angularfire#519]
I get this error when I delete all the text in the input field.
It seems that when the input field is empty, the property "name" on the object "user" is set to undefined instead of null.

View:

    <input type="text" ng-model="user.name">

Controller:

    var firebaseio = new Firebase(FIREBASE_URL);
    $firebase(firebaseio.child(USER_PATH)).$asObject().$bindTo($scope, "user");

So, how can I set it to null when the input field is cleared?

**Comment by woss** [comment]
Hi, maybe it's too late but here is my approach. Simple one though:
```
// view.html
<input ng-model="user.name" ng-change="change(user,'name')" type="text" placeholder="First Name" required>
```


```
// controller.js
// Prevent undefined data
  $scope.change = function (user,nodeName) {
  if(!angular.isDefined(user[nodeName]))
    {
      user[nodeName] = null;
    }
  }
```

**Comment by katowulf** [comment]
Another simple answer would just be to put a `.validate` rule on the records and ensure they always have a name. Enforcing data structure will save your code a lot of pain and complexity:  

```
"$record": {
     ".validate":  "newData.hasChild('name')",
     "name":  {
         ".validate":  "newData.isString() && newData.val().length > 0"
    }
}
```

**Comment by browndp08** [comment]
I'm confused as to why this issue is closed.  Adding ng-change to every form element is not a simple solution if you have an extended form.  And if you have multiple forms on different pages, you'll be rewriting $scope.change on every controller.  Not very DRY there.  @semeano will this issue be fixed in angularfire?  Angularfire provides tremendous ease in with its 3-way binding but I shouldn't have to rewrite every controller to get it to work on a simple input box.

**Comment by semeano** [comment]
@browndp08 I think this issue has been fixed, because I was trying to reproduce this issue and I couldn't. Instead the field was set with an empty string. Let me know.

**Comment by browndp08** [comment]
@semeano Thanks for looking into it.  I'm still getting the following error anytime I delete the value in my inputs.  

Error: Key .... was undefined. Cannot pass undefined in JSON. Use null instead.

**Comment by jwngr** [comment]
Make sure you are using the latest versions of Angular, AngularFire, and Firebase. Also, in order for us to help us, please put together a Plunker or JSFiddle with a repro.

**Comment by browndp08** [comment]
Yeah just created a fiddle and couldn't recreate the error.  Sorry guys I'll have to look deeper into my code to see what's going on.

**Comment by semeano** [comment]
@browndp08 Yep, I can confirm that. Adding "required" attribute causes that.
Although, if you want to validate the field, I recommend using angular validation instead of the default HTML5 validation.

Here's a nice tutorial: https://scotch.io/tutorials/angularjs-form-validation

**Comment by jorgehjr84** [comment]
Hey,I know this issue is closed, but this may help some people in the future. I was not using require and still got the error message 
"Error: Key name was undefined. Cannot pass undefined in JSON. Use null instead."

Thanks for the answers you guys posted, I tried them, but had issues getting those solutions to work in my certain instance. Here is what I did, it was really simple and worked perfectly. FYI, my app was a family tree and I left the "undefined" function off of the fields that would be required for my users.

```
$scope.submitCard = function() {
      $scope.cards.$add({
        name: $scope.newCardName,
        est: $scope.newCardEst,
        birthplace: $scope.newCardBirthplace,
        bio: optional($scope.newCardBio),
        phone: optional($scope.newCardPhone),
        email: optional($scope.newCardEmail)
      });

      function optional(card) {
        if (card) {
          return card;
        } else {
          return null;
        }
      };
```

Hope this helps

**Comment by katowulf** [comment]
Great idea, Jorge. For optional values and strings, a simple `$scope.variable || null` would work as well.

**Comment by browndp08** [comment]
@semeano after applying novalidate to the form element, I'm still getting an error.  You can see the same result on my jsfiddle at https://jsfiddle.net/kkwo9h5n/6/.  Any suggestions on how else I can validate a required field and make firebase work?

**Comment by semeano** [comment]
@browndp08 you're right. Let me check that.

**Comment by drewatk** [comment]
@semeano Any progress on this? My form is behaving like the jsfiddle that @browndp08 posted.

**Comment by semeano** [comment]
@drewatk For now the best solution is simply not using the HTML5 "required" directive. Use angular form validation instead: https://scotch.io/tutorials/angularjs-form-validation

**Comment by drewatk** [comment]
@semeano In that link they are using the regular HTML required directive. There is no equivalent angular directive.

**Comment by drewatk** [comment]
@semeano I used the ng-required="true" and it is working the exact same as required HTML5 directive. I still get this error and it causes my whole page's form not to be sent to firebase if there is a single empty field

**Comment by semeano** [comment]
@drewatk you're right, you'll have to do the validation by hand... I'm going to reopen this issue.

**Comment by katowulf** [comment]
Gents, can someone illuminate what this issue has to do with AngularFire? The interaction between ng-required, HTML5 required attributes, and form validation seems outside the scope of binding Firebase real-time data to Angular services.

**Comment by jwngr** [comment]
Also, @jorgehjr84 gave [a good workaround](https://github.com/firebase/angularfire/issues/519#issuecomment-120995046) a few comments previously.

**Comment by elpeyotl** [comment]
I had the exactly same problem. Was working in a project which I first was sending data to mongolab. I had to rewrite it using firebase. This error was showing up if the fields have been empty. They were no required fields, form was set to novalidate.  It was working with empty fields when sending to mongolab. So I think this could be a firebase specific problem? I only set my fields with ng-model. They do not have value in the controller. So probably workaround would be to set all fields first to $scope.field = null in controller? I used the good workaround with the function above and it worked. But well, strange that it is working with mongolab and not with firebase.

**Comment by katowulf** [comment]
Firebase/JSON do not accept undefined values in the data. ng-model also will not set values to undefined; however, if you have not declared a value for a $scope field, it can certainly be undefined.

If you attempt to place an undefined value into an AngularFire sync object/array, it's going to create an error. This is working as intended.

Further "I have the same problem" or +1's to this post will be deleted. Enough discussion.

**Comment by dkaushikl** [comment]
$scope.todos.$add({
            id: timestamp,
            name: '$scope.todoName',
            status: 'pending'
        });
that is not pass todoName Value

**Comment by jnelsontn** [comment]
This guide: https://github.com/firebase/angularfire/blob/master/docs/quickstart.md
Is more than likely why people are coming here. What it recommends, doesn't work and produces that result.
