### ISSUE TITLE
$signInWithPopup 'auth/popup-closed-by-user' error callback takes too many time

### ISSUE THREAD

**Issue by gabrielAnglada** [firebase/angularfire#849]
### Version info

**Angular: 1.5.8**

**Firebase: 3.x.x**

**AngularFire: 2.x.x**

### Steps to reproduce

Calling $signInWithPopup method opens a dialog to do oauth login. Then, close this dialog

### Expected behavior

When user closes oauth popup (google in this case), the error 'auth/popup-closed-by-user'  must fire inmmediately.

### Actual behavior

When user closes oauth popup (google in this case), the error 'auth/popup-closed-by-user' takes too many time to fire.

**Comment by jwngr** [comment]
Thanks for the report. We've gotten a few of these reports before. This is a problem with the underlying Firebase SDK, not AngularFire. As such, I'm going to close this issue in this repo. We don't have an official Firebase bug tracker, but I have logged an internal bug report and assigned it to our auth team. Hopefully they can look into it soon.

For our reference, how long does it normally take for you get the `auth/popup-closed-by-user` error?

**Comment by jwngr** [comment]
I'm told that this was actually fixed in the latest `3.3.0` release of the JavaScript SDK. This is noted in the [release notes for that release](https://firebase.google.com/support/release-notes/js#3.3.0). Please upgrade to the latest version and try again.

Also, in the future, it's important to share the *exact* version you are using, instead of a range, version since `3.x.x` includes a wide range of releases, each with different features and bug fixes.

**Comment by GeoffMahugu** [comment]
No,, still having the same issue: 
"@angular/cli": "^1.7.4",
"angularfire2": "^5.0.0-rc.6.0",
 "firebase": "^4.12.1",

**Comment by okosowski** [comment]
different frontend lib and  "firebase": "^9.1.2" and still there is no way to detect "close by user" action
